### ISSUE TITLE
Direct readout of characteristic quantities from snowfall

### ISSUE THREAD

**Issue by ltdeck** [SPL-ethz/snow#14]
Snowfall currently does not allow for an explicit argument to store states like snowflake. Consequently, the characteristic quantities (nucTemp etc) are automatically stored in stats_df, but not accessible via the direct functions, i.e. nucleationTemperatures(). This may be an issue since snowfall and snowflake behave different. For snowflake, direct access to the quantities is possible as of now. 

Code: 
```
from ethz_snow.snowfall import Snowfall
S = Snowfall(Nrep=10,N_vials=(3,3,1))
S.run()
S.plot(what="T_nucleation")
S.stats_df
S.nucleationTemperatures()
```

Screenshots:
![nostates](https://user-images.githubusercontent.com/83716040/135858258-3059955a-bd8b-479b-bacf-e1f299d3e16f.PNG)
![statsdf](https://user-images.githubusercontent.com/83716040/135858262-e6842441-a36d-47ae-b8f8-c2a345b61787.PNG)

**Comment by ltdeck** [comment]
The same issue was observed for the returnStats function
![returnstatus](https://user-images.githubusercontent.com/83716040/135867231-71c18f7d-0347-4abc-a722-895fc2cb47bf.PNG)

**Comment by bizzinho** [comment]
fixed in the commit that references this issue (see above)
