### ISSUE TITLE
Shelf temperature profile in plot function

### ISSUE THREAD

**Issue by ltdeck** [SPL-ethz/snow#15]
The current plot() function does not show the thermal evolution of the shelf. When selecting temperature trajectories, only those for the vials are shown. For validation, it would be helpful to also directly see the shelf temperature.

**Comment by ltdeck** [comment]
Code example:

from ethz_snow.snowflake import Snowflake
from ethz_snow.operatingConditions import OperatingConditions

 d = {"int": 20, "ext": 20, "s0": 20, "s_sigma_rel": 0} 
 S =Snowflake(storeStates='all',N_vials=(7,7,1),k=d,opcond=OperatingConditions(t_tot=1e4,cooling= {"rate": 5 / 60, "start": 20, "end": -50},holding= {"duration": 10, "temp": -12}))

S.run()

S.plot(kind='trajectories',what='temperature')

**Comment by bizzinho** [comment]
try it now, should work.

**Comment by ltdeck** [comment]
Works - very helpful indeed when designing holding steps.
