### ISSUE TITLE
Rewrite python code to use model-10

### ISSUE THREAD

**Issue by bizzinho** [SPL-ethz/snow#33]
See explanation here: https://www.overleaf.com/project/61c4470e0f950bebf892149d

**Comment by ltdeck** [comment]
Marco and I discussed this when finalizing the methods section for the manuscript. He agrees that model-8 / model-10 are equivalent, so no action required.

**Comment by bizzinho** [comment]
The math result is not _exactly_ the same, tho?

**Comment by bizzinho** [comment]
And the implementation here does not match the paper or do I misremember?

**Comment by ltdeck** [comment]
I would consider it as an addition, i.e. we provide the user with the option to select one of the two approaches. After all, the models are equivalent, i.e. no one is more correct than the other from a theoretical point of view, and the mathematical results differ by less than 0.1% in the initial amount of ice formed, i.e. solidification times differ by around 0.01%. Will discuss this in the comment. I agree with you, that we should set the standard option to the one described in the methods.

**Comment by bizzinho** [comment]
@ltdeck , need to actually add that code for model-10 as well into snowflake.py line 522 ;)

**Comment by ltdeck** [comment]
@bizzinho , I know. Have it on my to-do list. Thanks for the reminders ;)

**Comment by ltdeck** [comment]
@bizzinho I added it and did a validation of a box of vials, for which I found close agreement between the two methods. I wrote a few pages on this and added it to the validation file on overleaf. Please have a look.

**Comment by bizzinho** [comment]
Note for myself: d8cc4da38bf4bd4a7b7c741b0d2fa7ea9d67280c
